name: kijabewinds
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1c49b383-35d5-430d-8bda-d576f015c28a.png
layout_spectrum: 0.5116220228374004
typography_spectrum: 0.5221509071998298
style: the-composer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#433425'
    - '#eeeedc'
    - '#c0b594'
    - '#a9986f'
    - '#61533c'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
